#!/bin/bash

# QEMU keybindings
# ================
# C-a h    print this help
# C-a x    exit emulator
# C-a s    save disk data back to file (if -snapshot)
# C-a t    toggle console timestamps
# C-a b    send break (magic sysrq)
# C-a c    switch between console and monitor
# C-a C-a  sends C-a


exec qemu-system-x86_64 \
	-cdrom target/x86_64-unknown-lambix/release/lambix.iso \
	--enable-kvm \
	-no-reboot \
	-no-shutdown \
	-m 4G \
	-smp 4 \
	-nographic \
	"$@"
